language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.11.7

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test -Djava.util.Arrays.useLegacyMergeSort=true
